### ISSUE TITLE
Egyszem composer.json

### ISSUE THREAD

**Issue by szepeviktor** [Benjaminhu/szamlazz-php-api#1]
Üdvözöllek @Benjaminhu 👋🏻 

Erre a problémára a Composer-nak van beépített megoldása.
```json
{
    "name": "benjaminhu/projekt-ami-szamlaz",
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "szamlazzhu/php-sdk",
                "version": "2.10.18",
                "dist": {
                    "url": "https://www.szamlazz.hu/phpapi/PHPApiAgent-2.10.18.zip",
                    "type": "zip"
                },
                "autoload": {
                    "classmap": [
                        "src/szamlaagent/"
                    ]
                }
            }
        }
    ],
    "require": {
        "szamlazzhu/php-sdk": "^2.10"
    }
}
```
https://getcomposer.org/doc/05-repositories.md#package-2

És huss, mehetünk is tovább.

**Comment by Benjaminhu** [comment]
@szepeviktor WOW, köszi, erre a megoldási lehetőségre nem is gondoltam! Egy észrevétel jut csak eszembe, sajnos a régebbi verziók lekerülnek, pl. a `https://www.szamlazz.hu/phpapi/PHPApiAgent-2.10.16.zip` már nem elérhető és így teljesen random tud eltörni egy élesítés, mert már nem lesz ott a hivatkozott file. Ettől függetlenül zseniális, köszi, hogy megosztottad! Amennyiben beleegyezel a következő frissítéssel kiegészíteném majd ezzel a megoldással a README-t.

**Comment by szepeviktor** [comment]
> Amennyiben beleegyezel a következő frissítéssel kiegészíteném majd ezzel a megoldással a README-t.

Rendben!!

**Comment by szepeviktor** [comment]
Amelyik szerver egyszer már letöltötte az adott ZIP-et, ott a helyi cache-ben megmarad.

**Comment by szepeviktor** [comment]
> ott a helyi cache-ben megmarad.

Vagy beoperálható a cache könyvtárba egy jól irányzott `cp`-vel.

**Comment by Benjaminhu** [comment]
Ahová ez most megy ott Deployert használunk és külön release könyvtárakat, minden élesítéskor újra letölt mindent, tudom be lehetne állítani ott is cache-t. Apróság, de amikor beüt kellemetlen meglepetést okozhat.
