### ISSUE TITLE
Licencelés

### ISSUE THREAD

**Issue by szepeviktor** [Benjaminhu/szamlazz-php-api#2]
A ZIP fájljaiban nincs se licenc szöveg, se név.
Érdemes rákérdezni a KBOSS.hu-nál, hogyan állnak a dolgok.

[_forrás_](https://github.com/szepeviktor/github-repository-inspection)

**Comment by Benjaminhu** [comment]
@szepeviktor Köszi, szándékosan hagytam ki, már a csomagosítás is felvet kérdéseket, de kellett a projekthez :D folyamatban a dolog, remélem LinkedInen keresztül sikerül felvenni velük a kapcsolatot: https://www.linkedin.com/feed/update/urn:li:activity:7187748321120161792/

**Comment by szepeviktor** [comment]
Munka/pénz miatt nem érdemes a licencelésen átsiklani.
(de én nem vagyok vállalkozó fajta)
