### ISSUE TITLE
Csomag név

### ISSUE THREAD

**Issue by szepeviktor** [Benjaminhu/szamlazz-php-api#3]
A PHP forráskódban sok **zavaros** elnevezés van.

Az "API", amit a Számlázz.hu futtat a szervereiken.
Az API kliense az "SDK", ami kéréseket küld az API-nak.

Érdemes `szamlazzhu-php-sdk`-nak hívni ezt a csomagot.

**Comment by szepeviktor** [comment]
A helyes elnevezések lehetővé teszik, hogy tisztán gondolkodjunk valamiről.

**Comment by Benjaminhu** [comment]
@szepeviktor A kódban semmiképpen nem akartam módosítani, csak a könyvtár átnevezéseket csináltam meg a `PSR-4` miatt. A név is innen jött: `https://docs.szamlazz.hu/#php-api` a "szamlazz" prefixxel kiegészítve. És ha oda kerül esetleg a sor, hogy lesz hivatalos akkor valami ilyesmi lehetne valóban: `szamlazzhu/szamla-agent-php-sdk` vagy ha nem és én átnevezem akkor: `benjaminhu/szamlazz-szamla-agent-php-sdk`. Köszönöm az észrevételeket!

**Comment by szepeviktor** [comment]
A "Számla Agent" egy marketing név. Ezoterikus, azaz csak az érti, aki már tudja mi az.
